name: biobert_app
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.9
  - streamlit=1.41.1
  - pytorch::pytorch=1.13.1=cpu
  - pytorch::cpuonly
  - transformers=4.30.0
  - protobuf=3.20.0
  - accelerate=0.20.0
  - pip
  - pip:
    - --extra-index-url https://huggingface.github.io/hub-ci/
